config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root :to => 'welcome#index'

   post '/project/next_sprint' => 'project#next_sprint'
    resources :project do
      resources :sprint
      resources :tasks
    end
    resources :users

    

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :works
  has_many :users, through: :works 
  has_one :manager, class_name: "User"
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable
  has_many :works
  has_many :projects, through: :works
  
  def self.search(query)
  	where("email like ?", "%#{query}%") 
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end
end

app/models/work.rb
class Work < ActiveRecord::Base

  belongs_to :user, class_name: "User", foreign_key: "user_id"
  belongs_to :project, class_name: "Project", foreign_key: "project_id"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
 def google_oauth2 
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
	def new
		@project = Project.new
	end
	
	def index
		@project = Project.all
	end

	def show
    if current_user && current_user.id == Project.find(params[:id]).user_id
			@project = Project.find(params[:id])
			@user = User.all
			@tasks = Task.where(sprints: @project.current_sprint, project_id: params[:id])
			@options = (@project.current_sprint..@project.current_sprint+20)
			@task = Task.new
		elsif current_user && current_user.id != Project.find(params[:id]).user_id
			redirect_to user_path(current_user.id)
		else
			redirect_to new_user_session_path, notice: 'You are not logged in.'	
		end
	end

	def create
		@project = Project.new(params.require(:project).permit(:title, :text))
		@project.current_sprint = 0
		@project.user_id = current_user.id
		#@project.manager = current_user.id
		@project.save
		redirect_to project_path(@project.id)
  	end


end

app/controllers/sprint_controller.rb
class SprintController < ApplicationController
	def index
		@project = Project.find(params[:project_id])
		if current_user && @project.user_id == current_user.id
			@tasks = Task.where(sprints: @project.current_sprint, project_id: params[:project_id])
			render 'index'
		elsif current_user && @project.user_id != current_user.id
			redirect_to user_path(current_user.id)
		else
			redirect_to new_user_session_path

		end
	end

	def show
        @project = Project.find(params[:project_id])
        #render plain: @project.inspect
        @prev_task = Task.where(:project_id => params[:project_id]).where('(start_sprint= ?) OR 
        	(start_sprint < ? and sprints >= ?)',
         @project.current_sprint-1,@project.current_sprint-1,@project.current_sprint-1)
        @prev_comp = Task.where(:project_id => params[:project_id]).where('(start_sprint= ?) OR 
        	(start_sprint < ? and sprints = ?)',
         @project.current_sprint-1,@project.current_sprint-1,@project.current_sprint-1)
        @prev_incomp = Task.where(:project_id => params[:project_id]).where('(start_sprint= ?) OR 
        	(start_sprint < ? and sprints > ?)',
         @project.current_sprint-1,@project.current_sprint-1,@project.current_sprint-1)
    end


	public
	def create
		@project = Project.find(params[:project_id])
		@tasks = Task.where(project_id: params[:project_id], sprints: @project.current_sprint).where.not(status: 2)
		@project.current_sprint = @project.current_sprint+1
		@project.save
		@tasks.each do |t|
			t.sprints = t.sprints + 1
			t.save
		end
		redirect_to project_sprint_index_path
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	
    def index
        @tasks = Task.all
    end

    def show
        @task = Task.find(params[:id])
        @project = Project.find(params[:project_id])
        render plain: @project.inspect
        #@prev_task = Task.where(:project_id => params[:project_id]).where("start_sprint == @project.current_sprint-1 
        #    or (start_sprint < @project.current_spreint-1 and sprints >= @project.current_sprint-1)")
        #@prev_comp = Task.where(:project_id => params[:project_id]).where("start_sprint == @project.current_sprint-1 
        #    or (start_sprint < @project.current_spreint-1 and sprints == @project.current_sprint-1)")
        #@prev_incomp = Task.where(:project_id => params[:project_id]).where("start_sprint == @project.current_sprint-1 
        #    or (start_sprint < @project.current_spreint-1 and sprints > @project.current_sprint-1)")
    end
     
    def new
    	if current_user && current_user.id == Project.find(params[:project_id]).user_id
	        @task = Task.new
	        @project = Project.find(params[:project_id])
	        @user = User.all
	        @options = (@project.current_sprint..@project.current_sprint+20)
	    elsif current_user && current_user.id != Project.find(params[:project_id]).user_id
			redirect_to user_path(current_user.id)
		else
			redirect_to new_user_session_path, notice: 'You are not logged in.'	
		end
    end

    def edit
        @project = Project.find(params[:project_id])
        @options = ['In Progress', 'Not Started', 'Finished']
        redirect_to @project
    end

    def create
		@project = Project.find(params[:project_id])
		#render plain: project.inspect       
    	@task = @project.tasks.create(task_params)
    	@task.user_id = params[:user][:name]
    	@task.sprints = params[:sprints]
        @task.start_sprint = params[:sprints]
        @task.points = params[:task][:points]
    	@task.status = 0
    	#render plain: task.inspect
    	@task.save
    	redirect_to @project
    end

    def update
        @task = Task.find(params[:id])
        @task.status = params[:task][:status]
        @task.save
        redirect_to project_sprint_index_path(:project_id => @task.project_id)
    end
    private
    def task_params
      params.require(:task).permit(:text)
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		if current_user
			@projectlist = Project.where(user_id: current_user.id)
			@tasklist = Task.where(user_id: current_user.id)
		else
			#puts "please log in."
			redirect_to new_user_session_path, notice: 'You are not logged in.'
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
   if current_user
	redirect_to user_path(current_user.id)  
   end
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
  def create_new_dev
    @work = Work.new(user_id => @user.id, project_id => @project.id, role=> 'dev');
  end

  def create_new_proj_man
    @work = Work.new(user_id => @user.id, project_id => @project.id, role=> 'manager')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/sprint_helper.rb
module SprintHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sprint</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page-header">
	<% if user_signed_in? %>
	Signed in as <%= current_user.name %> (<%= current_user.id %>). Not you?
	<%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
	<% end %>
</div>
<%= yield %>
</body>
</html>

app/views/project/new.html.erb
<%= form_for :project, url: project_index_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/project/show.html.erb
<div class="jumbotron">
   <div class="container">
      		<h2><%= @project.title %></h2>
			<h4><%= @project.text %></h4>
    </div>
  </div>
	<div class="row">
	       <div class="col-lg-2">
	            <ul class="nav nav-pills nav-stacked">
		            <li><%= link_to 'Home', project_path %></li>
		            <li><%= link_to 'Profile', user_path %></li>
		            <li><%= link_to 'Add new task', new_project_task_path(:project_id => @project.id) %></li>
		            <li><%= link_to 'Sprint', project_sprint_index_path(:project_id => @project.id) %></li>
		            <li><%= link_to 'Last Sprint', project_sprint_path(:project_id => @project.id), method: :get %></li>
	            </ul>
       		</div>
       <div class="col-md-8">
			  <% if @project.tasks.count != 0 %>
				<h3>List of Tasks</h3>
				<table class="table table-bordered">
					<th> Task </th>
					<th> Assigned to </th>
					<th> Points </th>
					<th> Sprints </th>
					<% @project.tasks.each do |task| %>
					    <tr>
					    <td><%= task.text %></td>
					    <td><%= task.user.name %></td>
					    <% if task.points!= nil %>
					    	<td><%= task.points %></td>
					    <%else%>
					    	<td><%= 0 %></td>
					    <%end%>
					    <td><%= task.sprints %>
					    </tr>
					<% end %>
				</table>
				<% end %>
       </div>
    </div>
</div>

app/views/sprint/index.html.erb
<div class="jumbotron">
   <div class="container">
          <h2><%= @project.title %></h2>
      <h4><%= @project.text %></h4>
    </div>
  </div>

<div class="row">
         <div class="col-lg-2">
              <ul class="nav nav-pills nav-stacked">
                <li><%= link_to 'Home', project_path(:id => @project.id) %></li>
                <li><%= link_to 'Profile', user_path(:id => @project.user_id) %></li>
                <li><%= link_to 'Add new task', new_project_task_path(:project_id => @project.id) %></li>
                <li><%= link_to 'Sprint', project_sprint_index_path(:project_id => @project.id) %></li>
                <li><%= link_to 'Last Sprint', project_sprint_path(:project_id => @project.id, :id => @project.id), method: :get %></li>
              </ul>
          </div>

<div class="col-md-8">
  <h3>Current Sprint <%= @project.current_sprint %> </h3>
    <table class="table table-bordered">
        <th>Task Id</th>
        <th>Task</th>
        <th>Status</th>
        <th>Developer</th>
  	<% @tasks.each do |current_task| %>
      <tr>
        <td><%= current_task.id %></td>
  		  <td><%= current_task.text %></td>
  		  <td>
          <%= form_for current_task, url: project_task_path(project_id: @project.id, id: current_task.id), method: :put do |f| %>
            <%= f.radio_button :status, 0, :checked => (current_task.status == 0) %> 
            <%= label :status, "N" %> 
            <%= f.radio_button :status, 1, :checked => (current_task.status == 1) %>            
            <%= f.label :status, "P"  %>
            <%= f.radio_button :status, 2, :checked => (current_task.status == 2) %>
            <%= f.label :status, "F"  %>
            <%= f.submit %>
          <% end %>
        </td>
  		  <td><%= current_task.user.name %></td>
        <td>
        </td>
  		</tr>
  	<% end %>
  </table>

<%= form_for @project, url: project_sprint_index_path(project_id: @project.id), method: :post do |f| %>
	<%= f.submit "move to next sprint!"%>
<% end %>
</div>
</div>

app/views/sprint/show.html.erb
<div class="jumbotron">
   <div class="container">
      		<h2><%= @project.title %></h2>
			<h4><%= @project.text %></h4>
    </div>
  </div>
	<div class="row">
	       <div class="col-lg-2">
	            <ul class="nav nav-pills nav-stacked">
		            <li><%= link_to 'Home', project_path %></li>
		            <li><%= link_to 'Profile', user_path %></li>
		            <li><%= link_to 'Add new task', new_project_task_path(:project_id => @project.id) %></li>
		            <li><%= link_to 'Sprint', project_sprint_index_path(:project_id => @project.id) %></li>
		            <li><%= link_to 'Last Sprint', project_sprint_path(:project_id => @project.id), method: :get %></li>

	            </ul>
       		</div>
       <div class="col-md-8">
       		  <h3>Details of Last Sprint : <%= @project.current_sprint-1 %></h3>
			  <h4>Total Assigned Points : <%=@prev_task.sum(:points)%></h4>
			  <h4>Completed Points : <%=@prev_comp.sum(:points)%></h4>


			  <% if @project.tasks.count != 0 %>
				<h3>List of Completed Tasks</h3>
				<table class="table table-bordered">
					<th> Task </th>
					<th> Points </th>
					<% @prev_comp.each do |task| %>
					    <tr>
					    <td><%= task.text %></td>
					    <% if task.points!= nil %>
					    	<td><%= task.points %></td>
					    <%else%>
					    	<td><%= 0 %></td>
					    <%end%>
					    </tr>
					<% end %>
				</table>
			   <% end %>

			   <% if @project.tasks.count != 0 %>
				<h3>List of Pending Tasks</h3>
				<table class="table table-bordered">
					<th> Task </th>
					<th> Points </th>
					<% @prev_incomp.each do |task| %>
					    <tr>
					    <td><%= task.text %></td>
					    <% if task.points!= nil %>
					    	<td><%= task.points %></td>
					    <%else%>
					    	<td><%= 0 %></td>
					    <%end%>
					    </tr>
					<% end %>
				</table>
			   <% end %>
       </div>
    </div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>
 
<%= form_for :task, url: task_path(@task), method: :patch do |f| %>
 
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <h2>
  	Task id: @task.id
  </h2>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
  <p>Status Select
 	<%= select_tag "status", options_for_select(@options) %>
 	</p>

 	<p>Select Developer
 	<%= collection_select(:task, :name, @user, :id, :name, {:prompt => true}) %>
 </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<table>
  <tr>
    <th>User</th>
    <th>Task</th>
    <th colspan="2"></th>
  </tr>

  <% @tasks.each do |t| %>
    <tr>
      <td><%= t.user.name %></td>
      <td><%= t.text %></td>
      <td><%= link_to 'Show', task_path(t) %></td>
      <td><%= link_to 'Edit', edit_task_path(t) %></td>
    </tr>
  <% end %>
</table>

app/views/tasks/new.html.erb
<div class="jumbotron">
   <div class="container">
      		<h2><%= @project.title %></h2>
			<h4><%= @project.text %></h4>
    </div>
  </div>

<div class="row">
	       <div class="col-lg-2">
	            <ul class="nav nav-pills nav-stacked">
                <li><%= link_to 'Home', project_path(:id => @project.id) %></li>
                <li><%= link_to 'Profile', user_path(:id => @project.user_id) %></li>
                <li><%= link_to 'Add new task', new_project_task_path(:project_id => @project.id) %></li>
                <li><%= link_to 'Sprint', project_sprint_index_path(:project_id => @project.id) %></li>
                <li><%= link_to 'Last Sprint', project_sprint_path(:project_id => @project.id, :id => @project.id), method: :get %></li>
              </ul>
       		</div>

	<div class="col-md-8">
		<div class="container">
			<h4>Add a Task:</h4>
			<!-- <form role="form"> -->
			<%= form_for @task, url: project_tasks_path(project_id: @project.id) do |f| %>
			  <div class="form-group">
			    <%= f.label :text %>
			    <%= f.text_area :text, class: "form-control"%>
			  </div>
		   <div class="form-group">
		      <%= f.label :Points %>
		      <%= f.text_field :points, class: "form-control"%>
		    </div>
			  <div class="form-group">
			  <%= f.label :Developer %>
			  <%= collection_select(:user, :name, @user, :id, :name, {:prompt => true}, {class: "form-control"}) %>
			  </div>
			  <div class="form-group">
			  <%= f.label :Sprint %>
			  <%= select_tag "sprints", options_for_select(@options), class: "form-control" %>
			  </div>
			  <%= f.submit class: "btn"%>
			<% end %>
			<!-- </form> -->
		</div>
	</div>
</div>

app/views/tasks/show.html.erb
<h2>Details of the Task of the project id : @project.first.id </h2>
<table>
    <tr>
      <td>Project id : <%= @project.first.id %></td>
      <td>Task : <%= @task.text %></td>
      <td>Assigned Developer : <%= @task.user %></td>
      <td>Project Manager : <%= @task.project.manager %> </td>
      <td>Task Status :  <%= @task.status %> </td>
      <td>Task Sprint :  <%= @task.sprint %> </td>
    </tr>
</table>

app/views/users/show.html.erb
<div class="jumbotron">
   <div class="container">
      <h1 align = 'center'; style ="color:#8B008B; font-family:Lucida Console">Welcome <%= current_user.name %></h1>
    </div>
  </div>

<% if @projectlist.count == 0 %>
<h3 align='center' style="font-family:courier">You have not added any projects!</h3>

<% else %>

<h3 align='center' style="font-family:verdana">Projects you have Added:</h3>
<table align='center'>
<% @projectlist.each do |p| %>
    <tr>
      <td><%= link_to project_path(p.id) do %>
        <%= p.title %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<% end %>
<p></p>
<div class="span7 text-center">
<div class="btn-group">
  <button type="button" class="btn btn-default"><%= link_to "Add New Project", new_project_path %></button>
</div>
</div>
<p></p>
<% if @tasklist.count != 0 %>
<h3 align='center' style="font-family:verdana">Tasks You Have to Do :</h3>
<table align='center'>
  <tr>
    <th style="padding-right: 10px; padding-left: 10px">Task</th>
    <th style="padding-right: 10px; padding-left: 10px">Project Name</th>
    <th style="padding-right: 10px; padding-left: 10px">Sprint Assigned</th>
    <th style="padding-right: 10px; padding-left: 10px">Current Status</th>
  </tr>
<% @tasklist.each do |t| %>
    <tr>
      <td align='center'><%= t.text %></td>
      <td align='center'><%= link_to project_path(t.project_id) do %>
        <%= Project.find(t.project_id).title %>
        <% end %>
      </td>
      <td align='center'><%= t.sprints %></td>
      <% if t.status == 0 %>
      <td align='center'>Not Started</td>
      <% elsif t.status == 1 %>
      <td align='center'>Going On</td>
      <% else %>
      <td align='center'>Completed</td>
      <% end %>
    </tr>
  <% end %>
</table>
<% end %>
<p></p>

app/views/welcome/index.html.erb
<center>
 <h1>Welcome To Sprint-Management Software
 </h1>
<br/>
<%= button_to('Sign Up', new_user_registration_path, :class => 'btn btn-large btn-primary')  %>
<br/>
<%= button_to('Sign in', new_user_session_path, :class => 'btn btn-large btn-primary')  %>
<br/>
<%= button_to('Sign in with Google', user_omniauth_authorize_path(:google_oauth2), :class => 'btn btn-large btn-primary')  %>

</cente>